package com.activemap.export

import com.activemap.model.Activity
import com.activemap.model.Challenge
import com.activemap.model.Place
import kotlinx.datetime.Instant
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime

object MarkdownExporter {

    fun generateWeeklyReport(
        activities: List<Activity>,
        challenges: List<Challenge>,
        places: List<Place>,
        weekStart: Instant,
        weekEnd: Instant
    ): String {
        val sb = StringBuilder()

        sb.appendLine("# ActiveMap Weekly Report")
        sb.appendLine()
        sb.appendLine("**Period:** ${formatDate(weekStart)} — ${formatDate(weekEnd)}")
        sb.appendLine()

        // Summary
        val totalDuration = activities.sumOf { it.durationMinutes }
        val completedChallenges = challenges.count { it.completed }

        sb.appendLine("## Summary")
        sb.appendLine()
        sb.appendLine("- **Total Activities:** ${activities.size}")
        sb.appendLine("- **Total Duration:** ${formatDuration(totalDuration)}")
        sb.appendLine("- **Places Visited:** ${places.size}")
        sb.appendLine("- **Challenges Completed:** $completedChallenges / ${challenges.size}")
        sb.appendLine()

        // Activities
        if (activities.isNotEmpty()) {
            sb.appendLine("## Activities")
            sb.appendLine()
            activities.forEach { activity ->
                val place = places.find { it.id == activity.placeId }
                sb.appendLine("### ${place?.name ?: "Unknown Place"}")
                sb.appendLine("- **Date:** ${formatDate(activity.startedAt)}")
                sb.appendLine("- **Description:** ${activity.description}")
                sb.appendLine("- **Duration:** ${formatDuration(activity.durationMinutes)}")
                sb.appendLine("- **Status:** ${if (activity.completedAt != null) "Completed" else "In Progress"}")
                sb.appendLine()
            }
        }

        // Challenges
        if (challenges.isNotEmpty()) {
            sb.appendLine("## Challenges")
            sb.appendLine()
            challenges.forEach { challenge ->
                val status = if (challenge.completed) "✅ Completed" else "❌ Pending"
                sb.appendLine("- **${challenge.title}:** ${challenge.description} — $status")
            }
            sb.appendLine()
        }

        // Places
        if (places.isNotEmpty()) {
            sb.appendLine("## Places Visited")
            sb.appendLine()
            places.forEach { place ->
                sb.appendLine("- **${place.name}** (${place.type.name}) — ${place.description}")
            }
            sb.appendLine()
        }

        // Motivational message
        sb.appendLine("## Keep Going!")
        sb.appendLine()
        when {
            totalDuration > 300 -> sb.appendLine("Amazing week! You're building great habits. 💪")
            totalDuration > 120 -> sb.appendLine("Good progress! Keep the momentum going. 🏃")
            totalDuration > 0 -> sb.appendLine("Every step counts! Try to do a bit more next week. 🌱")
            else -> sb.appendLine("Start your fitness journey today! Every journey begins with a single step. 🚀")
        }
        sb.appendLine()
        sb.appendLine("---")
        sb.appendLine("*Generated by ActiveMap: AI-Coach for Beginners*")

        return sb.toString()
    }

    private fun formatDate(instant: Instant): String {
        val localDateTime = instant.toLocalDateTime(TimeZone.currentSystemDefault())
        return "${localDateTime.date} ${localDateTime.time.hour.toString().padStart(2, '0')}:${localDateTime.time.minute.toString().padStart(2, '0')}"
    }

    private fun formatDuration(minutes: Int): String {
        return when {
            minutes < 60 -> "${minutes}min"
            minutes == 60 -> "1h"
            else -> "${minutes / 60}h ${minutes % 60}min"
        }
    }
}
